FROM node:20-alpine AS migration_builder

WORKDIR /app

COPY package.json ./
COPY package-lock.json ./

RUN npm ci --omit=dev && npm install --no-save drizzle-kit drizzle-orm typescript tsx dotenv

COPY drizzle.config.ts ./
COPY src/app/lib/db/schema.ts ./src/app/lib/db/
COPY drizzle ./drizzle 

# the 'command' field in docker-compose will override this.
# CMD ["npx", "drizzle-kit", "migrate"]
