FROM node:20-alpine@sha256:fb4cd12c85ee03686f6af5362a0b0d56d50c58a04632e6c0fb8363f609372293 AS builder

WORKDIR /app

COPY package.json ./
COPY package-lock.json ./

RUN npm install --no-save \
    drizzle-kit \
    drizzle-orm \
    typescript \
    tsx \
    dotenv

COPY drizzle.config.ts ./
COPY src/lib/db/schema.ts ./src/lib/db/ 
COPY drizzle ./drizzle

FROM node:20-alpine@sha256:fb4cd12c85ee03686f6af5362a0b0d56d50c58a04632e6c0fb8363f609372293 AS migrator_runtime

WORKDIR /app

COPY --from=builder /app/node_modules ./node_modules/

COPY --from=builder /app/drizzle.config.ts ./
COPY --from=builder /app/src/lib/db/schema.ts ./src/lib/db/
COPY --from=builder /app/drizzle ./drizzle

# the 'command' field in docker-compose will override this.
# CMD ["npx", "drizzle-kit", "migrate"]
