services: 
  immoly-app: 
    container_name: immoly-app
    depends_on: 
      - immoly-postgres
    image: ghcr.io/davidcode2/immoly:${IMAGE_TAG:-latest}
    restart: unless-stopped
    networks: 
      - app-network
      - immoly-network
    env_file:
      - ./.env
    
  immoly-postgres:
    container_name: immoly-postgres
    image: postgres:16.0-alpine
    restart: unless-stopped
    volumes: 
      - immoly-volume:/var/lib/postgresql/data
    networks: 
      - immoly-network
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

volumes: 
  immoly-volume:

networks:
  immoly-network:
  app-network:
    external: true
